#1=검침원 5= 타사 9= 마스터
#HOME
ISTC_F1=1579
#원격검침현황
ISTC_F2=1579
#원격검침집계
ISTC_F3=179
#원격검침내역
ISTC_F4=179
#등록이력관리
ISTC_F6=
#수용가정보
ISTC_F8=179
#수검침
ISTC_F9=
#부과조회
ISTC_F10=179
#설정
SETTING_GRP=579
#누수검출기능
ISTC_WATERWEEK_GRP=79
#누수검출
ISTC_F11_1=
#누수검출-설정
ISTC_F11_3=79
#사용자 관리-마스터
ISTC_F5_1=9
#사용자 관리
ISTC_F5_1_1=7
#종합등록 관리
ISTC_F5_2=579
#LG 서비스코드 관리
ISTC_F5_SVC_LIST=579
#부수용가 등록
ISTC_F5_6=79
#하향URL 관리
ISTC_F5_URL_RTS=9
#장비 설정
ISTC_F5_SEND_RTS=9
#명령 이력
ISTC_F5_SEND_RTS_HISTORY=9
#DB에러로그
ISTC_F12=9
#유지보수 그룹
SM_GRP=9
#시간대별 검침값검출
ISTC_F13=79