# 이름 설정
spring.application.name=icbm_boot
# 포트설정
server.port = 8080
# 로그 타입 설정. 
# 운영 = INFO 로컬,개발 = DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.com.mybatis.mapper=DEBUG
logging.level.com.istec=DEBUG
#캐쉬 사용x
spring.resources.cache.cachecontrol.no-store=true


########### DATABASE 설정 ############
#spring.datasource.url=jdbc:postgresql://211.53.249.241:5432/mars_icbm
# spring.datasource.url=jdbc:postgresql://211.53.249.251:5435/mars_icbm
spring.datasource.url=jdbc:postgresql://211.53.249.251:5436/mars_icbm

#spring.datasource.url=jdbc:postgresql://111.1.4.87:5432/mars_icbm
#spring.datasource.url=jdbc:postgresql://172.100.100.241:5432/mars_icbm
spring.datasource.username=mars_icbm
spring.datasource.password=mars@icbm
spring.datasource.driver-class-name=org.postgresql.Driver
mybatis.mapper-locations=classpath:/mapper/postgreSql/*.xml
spring.transaction.default-timeout=180
spring.transaction.rollback-on-commit-failure=true 


############ VIEW 설정 #####################
spring.mvc.view.prefix:/WEB-INF/views/
spring.mvc.view.suffix:.jsp
server.servlet.jsp.init-parameters.development=true

#리소스 실시간반영
spring.devtools.restart.enabled=false

#파일 업로드
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB



########리소스 설정##############
spring.mvc.static-path-pattern=/resources/**
spring.web.resources.static-locations=classpath:/static/,classpath:/public/,classpath:/resources/


############### 소스코드 쪽 설정 ###############
#파일 인터벌.
file.expireInterval	= 600000

#v월드 라이센스 지도. OSM 사용시 무시
vLicense=20B6D7AF-BE14-35C7-BA46-B1906211FBA4


############### 건들면안됨 ###############
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true 
spring.main.allow-bean-definition-overriding=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
server.error.whitelabel.enabled=false

