<!-- jsgrid component -->
<link rel="stylesheet" type="text/css" href="${contextPath}/resources/page/common/css/istc-jsgrid-theme.css">
<link rel="stylesheet" type="text/css" href="${contextPath}/resources/lib/jsgrid-1.5.3/jsgrid.css" />
<script type="text/javascript" src="${contextPath}/resources/lib/jsgrid-1.5.3/jsgrid.ext.js"></script>
<script type="text/javascript" src="${contextPath}/resources/page/common/js/istc-jsgrid-ext.js"></script>

<link rel="stylesheet" type="text/css" href="${contextPath}/resources/page/common/css/jsgrid-custom.css">
