<!-- Map with Open Layer -->
<link rel="stylesheet" type="text/css" href="${contextPath}/resources/lib/ol3-ext-1.0.1/ol.css?v=1.00">
<script type="text/javascript" src="${contextPath}/resources/lib/ol3-ext-1.0.1/ol.js?v=1.00"></script>

<link rel="stylesheet" type="text/css" href="${contextPath}/resources/lib/ol3-ext-1.0.1/ol3-ext.css">
<script type="text/javascript" src="${contextPath}/resources/lib/ol3-ext-1.0.1/ol3-ext.min.js"></script>

<link rel="stylesheet" type="text/css" href="${contextPath}/resources/page/gis/css/layerswitcher.css">
<script type="text/javascript" src="${contextPath}/resources/page/gis/js/layerswitcher.js"></script>

<link rel="stylesheet" type="text/css" href="${contextPath}/resources/page/gis/css/ol.css">
<script type="text/javascript" src="${contextPath}/resources/page/gis/js/ol_drag.js"></script>
<script type="text/javascript" src="${contextPath}/resources/page/gis/js/ol_map.js"></script>	
<script type="text/javascript" src="${contextPath}/resources/page/gis/js/ol_util.js"></script>
<script type="text/javascript" src="${contextPath}/resources/page/gis/js/ol_layer_base.js"></script>	
<script type="text/javascript" src="${contextPath}/resources/page/gis/js/ol_layer_meter.js?v=1.04"></script>