<!-- jquery Validation component -->
<script type="text/javascript" src="${contextPath}/resources/lib/jquery.validation/jquery.validate.js"></script>
<script type="text/javascript" src="${contextPath}/resources/lib/jquery.validation/additional-methods.js"></script>
<script type="text/javascript" src="${contextPath}/resources/lib/jquery.validation/messages_ko.js"></script>
<script type="text/javascript" src="${contextPath}/resources/lib/jquery.validation/validateRule.js?v=1.0"></script>